# Generated by Django 5.1.2 on 2024-10-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logged',
        ),
    ]
