# Generated by Django 5.1.2 on 2024-10-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_login_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=122)),
                ('name2', models.CharField(max_length=122)),
                ('name3', models.CharField(max_length=122)),
                ('name4', models.CharField(max_length=122)),
            ],
        ),
    ]
